# Generated by Django 4.0.1 on 2022-01-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('country_code', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('prefix', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.TextField(null=True)),
                ('temp', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('language', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.language')),
            ],
        ),
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.userprofile')),
                ('weather', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.weather')),
            ],
        ),
    ]
