# Generated by Django 4.0.1 on 2022-01-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='city_name',
        ),
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.cities'),
        ),
    ]
