# Generated by Django 4.0.1 on 2022-01-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_weather_city_name_weather_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='app_temp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_speed',
            field=models.TextField(null=True),
        ),
    ]
