# Generated by Django 4.0 on 2021-12-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_error'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
