# Generated by Django 4.0 on 2021-12-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_userprofile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.AlterField(
            model_name='histories',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
