# Generated by Django 4.0 on 2021-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_delete_error_alter_histories_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histories',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
