# Generated by Django 4.0 on 2021-12-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_histories_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='types',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
