# Generated by Django 4.0 on 2021-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_countries_id_alter_types_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='histories',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
